name:                underload-hs
version:             0.1.0.0
github:              "mercerenies/underload-hs"
license:             AllRightsReserved
author:              "Silvio Mayolo"
copyright:           "2025 Silvio Mayolo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/underload-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.7 && < 1
- mtl >= 2.3 && < 3
- parsec >= 3.1 && < 4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing  # Why is this one a thing?

library:
  source-dirs: src

executables:
  underload-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - underload-hs

tests:
  underload-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - underload-hs
